[project]
name = "ai-examples"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "agent-sandbox==0.0.14",
    "google-adk>=1.10.0",
    "huggingface-hub>=0.34.4",
    "litellm>=1.75.5.post1",
    "playwright>=1.55.0",
]
